name: MAKO Rate Update

on:
  schedule:
    # Horarios convertidos de PET (Perú) a UTC:
    - cron: '30 12 * * *' # 07:30 AM Perú
    - cron: '0 13 * * *'  # 08:00 AM Perú
    - cron: '30 13 * * *' # 08:30 AM Perú
    - cron: '0 14 * * *'  # 09:00 AM Perú
    - cron: '0 21 * * *'  # 04:00 PM Perú
    - cron: '0 22 * * *'  # 05:00 PM Perú
  workflow_dispatch: # Para ejecutarlo manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  #
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests # He simplificado aquí por si no quieres usar requirements.txt externo

      - name: Run Scraper
        run: python cambio.py # Ejecuta tu lógica de apis.net.pe
        
      - name: Commit changes
        run: |
          git config --global user.name "LuxBot"
          git config --global user.email "bot@mako.pro"
          git add rate.json
          git commit -m "Radar Update: $(date)" || exit 0
          git push